version: '3'
services:
  pg-tasks:
    container_name: pg-tasks
    image: postgres:9.6
    ports:
      - 5433:5432  # porta externa:porta interna em relação ao container
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=password